-- To run this file, you need to install the REST Client extension in Visual Studio Code
-- Select the code below and right-click, then select "Send Request" to run the code

get http://127.0.0.1:5000

get http://127.0.0.1:5000/ping

-- Transcribe Audio
POST http://127.0.0.1:5000/transcribe-ai HTTP/1.1
content-type: application/json

{
    "video_url": "https://youtu.be/sj_Uq6zsqPo?si=PXANunv5JDZY8Per"
}


-- Summarize Audio
POST http://127.0.0.1:5000/summarize-ai HTTP/1.1
content-type: application/json

{
    "video_url": "https://www.youtube.com/watch?v=ZageOcTQdM0"
}


-- Extrct References
POST http://127.0.0.1:5000/extract-references HTTP/1.1
content-type: application/json

{
    "video_url": "https://www.youtube.com/watch?v=ZageOcTQdM0"
}


-- Generate Articles JSON
POST http://127.0.0.1:5000/generate-article-json HTTP/1.1
content-type: application/json

{
    "video_url": "https://www.youtube.com/watch?v=ZageOcTQdM0"
}

-- Generate Articles HTML (without passing the article json)
POST http://127.0.0.1:5000/generate-article-html HTTP/1.1
content-type: application/json

{
    "video_url": "https://www.youtube.com/watch?v=ZageOcTQdM0"
}